# Generated by Django 5.1.3 on 2024-12-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=50, verbose_name='Drug Name')),
                ('drug_brand', models.CharField(max_length=50, verbose_name='Drug Brand')),
                ('drug_dosage_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Drug Dosage Value')),
                ('drug_dosage_unit', models.CharField(choices=[('mcg', 'Microgram'), ('mg', 'Milligram'), ('g', 'Gram'), ('ml', 'Milliliter'), ('iu', 'International Unit')], max_length=5, verbose_name='Drug Dosage Unit')),
                ('drug_quantity', models.PositiveIntegerField(verbose_name='Quantity in Stock')),
                ('drug_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per Unit')),
                ('production_date', models.DateField(verbose_name='Production Date')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
            ],
            options={
                'verbose_name': 'Drug',
                'verbose_name_plural': 'Drugs',
                'ordering': ['drug_name'],
                'constraints': [models.UniqueConstraint(fields=('drug_name', 'drug_dosage_value', 'drug_dosage_unit', 'drug_brand'), name='unique_drug_constraint')],
            },
        ),
    ]
