# Generated by Django 5.1.3 on 2024-12-19 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0003_alter_drug_options_and_more'),
        ('pharma', '0002_alter_pharmacy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drugs', to='pharma.pharmacy'),
        ),
    ]
