# Generated by Django 5.1.3 on 2024-12-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(max_length=50, verbose_name='Pharmacy Name')),
                ('pharmacy_address', models.CharField(max_length=400, unique=True, verbose_name='Pharmacy Address')),
            ],
            options={
                'verbose_name': 'Pharmacy',
                'verbose_name_plural': 'Pharmacies',
                'ordering': ['pharmacy_name'],
            },
        ),
    ]
