# Generated by Django 5.1.3 on 2024-12-16 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_alter_purchaseitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='price',
        ),
    ]
