# Generated by Django 5.1.3 on 2024-12-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_remove_purchase_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Price per unit'),
        ),
    ]
